version: "3"

services:
  server:
    build: .
    ports:
      - "5000:5000" # Chat server port
      - "5900:5900" # VNC port
    volumes:
      - ./chat:/opt/chat/chat # For persistent chat history and credentials
    command: ["/bin/bash", "/opt/chat/startapp_server.sh"]
    environment:
      - DISPLAY=:0
    network_mode: "host"

  client:
    build: .
    ports:
      - "5901:5900" # VNC port for client
    volumes:
      - ./chat:/opt/chat/chat # For persistent chat history and credentials
    command: ["/bin/bash", "/opt/chat/startapp_client.sh"]
    environment:
      - DISPLAY=:0
    network_mode: "host"
    depends_on:
      - server
