version: '3.8'

services:
  server:
    build: .
    container_name: server
    environment:
      - DISPLAY=host.docker.internal:0
    volumes:
      - chatdata:/app/chat
    networks:
      - chat-network
    restart: always

  client:
    build: .
    environment:
      - DISPLAY=host.docker.internal:0
    entrypoint: [ "java", "chat.ClientGUI" ]
    volumes:
      - chatdata:/app/chat
    networks:
      - chat-network
    restart: always

networks:
  chat-network:
    driver: bridge

volumes:
  chatdata:
